FROM openjdk:17

ARG USERVICE_HOME=/opt/app/

# Build up the deployment folder structure
RUN mkdir -p $USERVICE_HOME

ADD biometric-nbi-*.jar $USERVICE_HOME/ROOT.jar
#ADD application_default_credentials.json application_default_credentials.json

#ARG GOOGLE_APPLICATION_CREDENTIALS=application_default_credentials.json
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/opt/app/ROOT.jar"]

