#FROM anapsix/alpine-java:jre8
FROM openjdk:17

ARG USERVICE_HOME=/opt/app/

# Build up the deployment folder structure
RUN mkdir -p $USERVICE_HOME

ADD biometric-nbi-*.jar $USERVICE_HOME/ROOT.jar
ADD application_default_credentials.json application_default_credentials.json
#ADD startService.sh $USERVICE_HOME/bin/

ARG GOOGLE_APPLICATION_CREDENTIALS=application_default_credentials.json
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/opt/app/ROOT.jar"]

#CMD ["/opt/app/bin/startService.sh"]