apiVersion: v1
kind: Service
metadata:
  name: biometric-nbi
  namespace: biometric
  labels:
    app: biometric-nbi
spec:
  type: NodePort
  selector:
    app: biometric-nbi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30888