# 2025 michael at obrienlabs.cloud
# https://github.com/ObrienlabsDev/biometric-backend
# depends on namespace
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: kubernetes.io/basic-auth
stringData:
  password: password
  