apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  # kubectl port-forward mysql-58b7767464-dgpf4 3306:3306
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
  clusterIP: None